// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AnimationOverPictures","status":true,"description":"アニメーションを、ピクチャより前に表示します。","parameters":{}},
{"name":"TMMoveEx","status":true,"description":"壁衝突音やリージョンによる通行設定などの機能を追加します。","parameters":{"passableRegionId":"251","dontPassRegionId":"252","seKnockWall":"<name:Blow1><volume:0><pitch:100>","knockWallPan":"75","knockWallInterval":"30","turnKeyCode":"83","movableRegion1":"","movableRegion2":"","movableRegion3":"","movableRegion4":"","movableRegion5":"","movableRegion6":"","movableRegion7":"","movableRegion8":"","movableRegion9":"","movableRegion10":""}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"-150","Offset Y":"-70","Width":"240","Background":"2"}},
{"name":"ponidog_BackLog_utf8","status":true,"description":"バックログ及びメッセージ周りの補填関係","parameters":{"nBackLogDisplayLine":"12","nBackLogLimitMax":"-1","nBackLogButtonUp":"0","nBackLogButtonDown":"0","nBackLogButtonHide":"0","bBackLogNameOn_forYepMessageCore":"true","bBackLogNameOn_Flame":"●","bBackLogNameOn_Flame2":"","sBackLogNoFaceSymbol":"★","sBackLogNoFaceSpace":""}},
{"name":"YEP_MessageCore","status":true,"description":"v1.02 Adds more features to the Message Window to customized\nthe way your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward":"Input.isPressed('pagedown')","Word Wrapping":"false","Description Wrap":"false","---Font---":"","Font Name":"GameFont","Font Size":"18","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]"}},
{"name":"StartUpFullScreen","status":true,"description":"フルスクリーンで起動プラグイン","parameters":{"シャットダウン":"シャットダウン","フルスクリーンで起動":"フルスクリーンで起動"}},
{"name":"UTA_MessageSkip","status":true,"description":"特定キーを押す事でメッセージをスキップできるようにします。","parameters":{"Skip Key":"control","Show Trace":"false"}},
{"name":"HPMPLVInvisible","status":true,"description":"HP・MP・レベルを非表示にできます","parameters":{"isVisibleHP":"0","isVisibleMP":"0","isVisibleLV":"0"}},
{"name":"VE_Single_Actor","status":true,"description":"One-Actor's menu. This plugin is made for one playable actor only.","parameters":{"Level Number x Distance":"50","Class text x Distance":"160","ExptoLvl text x Distance":"160","Status Window Width":"325"}},
{"name":"NpcFollower","status":true,"description":"NPCフォロワープラグイン","parameters":{"最大同時NPC数":"1"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.3) 指定された番号のスイッチがONの間、\nプレイヤー操作によるキャラの移動を禁止します。","parameters":{"Default_Move_Flag":"10","Default_Menu_Flag":"true"}},
{"name":"EasingPicture","status":true,"description":"ピクチャーの移動パターンを増やします。","parameters":{}}
];
